# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zxe/Documents/BXC_RtspServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zxe/Documents/BXC_RtspServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zxe/Documents/BXC_RtspServer/CMakeFiles /home/zxe/Documents/BXC_RtspServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zxe/Documents/BXC_RtspServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BXC_RtspServer

# Build rule for target.
BXC_RtspServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BXC_RtspServer
.PHONY : BXC_RtspServer

# fast build rule for target.
BXC_RtspServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/build
.PHONY : BXC_RtspServer/fast

trunk/Live/AACFileMediaSource.o: trunk/Live/AACFileMediaSource.cpp.o
.PHONY : trunk/Live/AACFileMediaSource.o

# target to build an object file
trunk/Live/AACFileMediaSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/AACFileMediaSource.cpp.o
.PHONY : trunk/Live/AACFileMediaSource.cpp.o

trunk/Live/AACFileMediaSource.i: trunk/Live/AACFileMediaSource.cpp.i
.PHONY : trunk/Live/AACFileMediaSource.i

# target to preprocess a source file
trunk/Live/AACFileMediaSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/AACFileMediaSource.cpp.i
.PHONY : trunk/Live/AACFileMediaSource.cpp.i

trunk/Live/AACFileMediaSource.s: trunk/Live/AACFileMediaSource.cpp.s
.PHONY : trunk/Live/AACFileMediaSource.s

# target to generate assembly for a file
trunk/Live/AACFileMediaSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/AACFileMediaSource.cpp.s
.PHONY : trunk/Live/AACFileMediaSource.cpp.s

trunk/Live/AACFileSink.o: trunk/Live/AACFileSink.cpp.o
.PHONY : trunk/Live/AACFileSink.o

# target to build an object file
trunk/Live/AACFileSink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/AACFileSink.cpp.o
.PHONY : trunk/Live/AACFileSink.cpp.o

trunk/Live/AACFileSink.i: trunk/Live/AACFileSink.cpp.i
.PHONY : trunk/Live/AACFileSink.i

# target to preprocess a source file
trunk/Live/AACFileSink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/AACFileSink.cpp.i
.PHONY : trunk/Live/AACFileSink.cpp.i

trunk/Live/AACFileSink.s: trunk/Live/AACFileSink.cpp.s
.PHONY : trunk/Live/AACFileSink.s

# target to generate assembly for a file
trunk/Live/AACFileSink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/AACFileSink.cpp.s
.PHONY : trunk/Live/AACFileSink.cpp.s

trunk/Live/Buffer.o: trunk/Live/Buffer.cpp.o
.PHONY : trunk/Live/Buffer.o

# target to build an object file
trunk/Live/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Buffer.cpp.o
.PHONY : trunk/Live/Buffer.cpp.o

trunk/Live/Buffer.i: trunk/Live/Buffer.cpp.i
.PHONY : trunk/Live/Buffer.i

# target to preprocess a source file
trunk/Live/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Buffer.cpp.i
.PHONY : trunk/Live/Buffer.cpp.i

trunk/Live/Buffer.s: trunk/Live/Buffer.cpp.s
.PHONY : trunk/Live/Buffer.s

# target to generate assembly for a file
trunk/Live/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Buffer.cpp.s
.PHONY : trunk/Live/Buffer.cpp.s

trunk/Live/H264FileMediaSource.o: trunk/Live/H264FileMediaSource.cpp.o
.PHONY : trunk/Live/H264FileMediaSource.o

# target to build an object file
trunk/Live/H264FileMediaSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/H264FileMediaSource.cpp.o
.PHONY : trunk/Live/H264FileMediaSource.cpp.o

trunk/Live/H264FileMediaSource.i: trunk/Live/H264FileMediaSource.cpp.i
.PHONY : trunk/Live/H264FileMediaSource.i

# target to preprocess a source file
trunk/Live/H264FileMediaSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/H264FileMediaSource.cpp.i
.PHONY : trunk/Live/H264FileMediaSource.cpp.i

trunk/Live/H264FileMediaSource.s: trunk/Live/H264FileMediaSource.cpp.s
.PHONY : trunk/Live/H264FileMediaSource.s

# target to generate assembly for a file
trunk/Live/H264FileMediaSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/H264FileMediaSource.cpp.s
.PHONY : trunk/Live/H264FileMediaSource.cpp.s

trunk/Live/H264FileSink.o: trunk/Live/H264FileSink.cpp.o
.PHONY : trunk/Live/H264FileSink.o

# target to build an object file
trunk/Live/H264FileSink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/H264FileSink.cpp.o
.PHONY : trunk/Live/H264FileSink.cpp.o

trunk/Live/H264FileSink.i: trunk/Live/H264FileSink.cpp.i
.PHONY : trunk/Live/H264FileSink.i

# target to preprocess a source file
trunk/Live/H264FileSink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/H264FileSink.cpp.i
.PHONY : trunk/Live/H264FileSink.cpp.i

trunk/Live/H264FileSink.s: trunk/Live/H264FileSink.cpp.s
.PHONY : trunk/Live/H264FileSink.s

# target to generate assembly for a file
trunk/Live/H264FileSink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/H264FileSink.cpp.s
.PHONY : trunk/Live/H264FileSink.cpp.s

trunk/Live/InetAddress.o: trunk/Live/InetAddress.cpp.o
.PHONY : trunk/Live/InetAddress.o

# target to build an object file
trunk/Live/InetAddress.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/InetAddress.cpp.o
.PHONY : trunk/Live/InetAddress.cpp.o

trunk/Live/InetAddress.i: trunk/Live/InetAddress.cpp.i
.PHONY : trunk/Live/InetAddress.i

# target to preprocess a source file
trunk/Live/InetAddress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/InetAddress.cpp.i
.PHONY : trunk/Live/InetAddress.cpp.i

trunk/Live/InetAddress.s: trunk/Live/InetAddress.cpp.s
.PHONY : trunk/Live/InetAddress.s

# target to generate assembly for a file
trunk/Live/InetAddress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/InetAddress.cpp.s
.PHONY : trunk/Live/InetAddress.cpp.s

trunk/Live/MediaSession.o: trunk/Live/MediaSession.cpp.o
.PHONY : trunk/Live/MediaSession.o

# target to build an object file
trunk/Live/MediaSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSession.cpp.o
.PHONY : trunk/Live/MediaSession.cpp.o

trunk/Live/MediaSession.i: trunk/Live/MediaSession.cpp.i
.PHONY : trunk/Live/MediaSession.i

# target to preprocess a source file
trunk/Live/MediaSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSession.cpp.i
.PHONY : trunk/Live/MediaSession.cpp.i

trunk/Live/MediaSession.s: trunk/Live/MediaSession.cpp.s
.PHONY : trunk/Live/MediaSession.s

# target to generate assembly for a file
trunk/Live/MediaSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSession.cpp.s
.PHONY : trunk/Live/MediaSession.cpp.s

trunk/Live/MediaSessionManager.o: trunk/Live/MediaSessionManager.cpp.o
.PHONY : trunk/Live/MediaSessionManager.o

# target to build an object file
trunk/Live/MediaSessionManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSessionManager.cpp.o
.PHONY : trunk/Live/MediaSessionManager.cpp.o

trunk/Live/MediaSessionManager.i: trunk/Live/MediaSessionManager.cpp.i
.PHONY : trunk/Live/MediaSessionManager.i

# target to preprocess a source file
trunk/Live/MediaSessionManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSessionManager.cpp.i
.PHONY : trunk/Live/MediaSessionManager.cpp.i

trunk/Live/MediaSessionManager.s: trunk/Live/MediaSessionManager.cpp.s
.PHONY : trunk/Live/MediaSessionManager.s

# target to generate assembly for a file
trunk/Live/MediaSessionManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSessionManager.cpp.s
.PHONY : trunk/Live/MediaSessionManager.cpp.s

trunk/Live/MediaSource.o: trunk/Live/MediaSource.cpp.o
.PHONY : trunk/Live/MediaSource.o

# target to build an object file
trunk/Live/MediaSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSource.cpp.o
.PHONY : trunk/Live/MediaSource.cpp.o

trunk/Live/MediaSource.i: trunk/Live/MediaSource.cpp.i
.PHONY : trunk/Live/MediaSource.i

# target to preprocess a source file
trunk/Live/MediaSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSource.cpp.i
.PHONY : trunk/Live/MediaSource.cpp.i

trunk/Live/MediaSource.s: trunk/Live/MediaSource.cpp.s
.PHONY : trunk/Live/MediaSource.s

# target to generate assembly for a file
trunk/Live/MediaSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/MediaSource.cpp.s
.PHONY : trunk/Live/MediaSource.cpp.s

trunk/Live/Rtp.o: trunk/Live/Rtp.cpp.o
.PHONY : trunk/Live/Rtp.o

# target to build an object file
trunk/Live/Rtp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Rtp.cpp.o
.PHONY : trunk/Live/Rtp.cpp.o

trunk/Live/Rtp.i: trunk/Live/Rtp.cpp.i
.PHONY : trunk/Live/Rtp.i

# target to preprocess a source file
trunk/Live/Rtp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Rtp.cpp.i
.PHONY : trunk/Live/Rtp.cpp.i

trunk/Live/Rtp.s: trunk/Live/Rtp.cpp.s
.PHONY : trunk/Live/Rtp.s

# target to generate assembly for a file
trunk/Live/Rtp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Rtp.cpp.s
.PHONY : trunk/Live/Rtp.cpp.s

trunk/Live/RtspConnection.o: trunk/Live/RtspConnection.cpp.o
.PHONY : trunk/Live/RtspConnection.o

# target to build an object file
trunk/Live/RtspConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/RtspConnection.cpp.o
.PHONY : trunk/Live/RtspConnection.cpp.o

trunk/Live/RtspConnection.i: trunk/Live/RtspConnection.cpp.i
.PHONY : trunk/Live/RtspConnection.i

# target to preprocess a source file
trunk/Live/RtspConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/RtspConnection.cpp.i
.PHONY : trunk/Live/RtspConnection.cpp.i

trunk/Live/RtspConnection.s: trunk/Live/RtspConnection.cpp.s
.PHONY : trunk/Live/RtspConnection.s

# target to generate assembly for a file
trunk/Live/RtspConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/RtspConnection.cpp.s
.PHONY : trunk/Live/RtspConnection.cpp.s

trunk/Live/RtspServer.o: trunk/Live/RtspServer.cpp.o
.PHONY : trunk/Live/RtspServer.o

# target to build an object file
trunk/Live/RtspServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/RtspServer.cpp.o
.PHONY : trunk/Live/RtspServer.cpp.o

trunk/Live/RtspServer.i: trunk/Live/RtspServer.cpp.i
.PHONY : trunk/Live/RtspServer.i

# target to preprocess a source file
trunk/Live/RtspServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/RtspServer.cpp.i
.PHONY : trunk/Live/RtspServer.cpp.i

trunk/Live/RtspServer.s: trunk/Live/RtspServer.cpp.s
.PHONY : trunk/Live/RtspServer.s

# target to generate assembly for a file
trunk/Live/RtspServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/RtspServer.cpp.s
.PHONY : trunk/Live/RtspServer.cpp.s

trunk/Live/Sink.o: trunk/Live/Sink.cpp.o
.PHONY : trunk/Live/Sink.o

# target to build an object file
trunk/Live/Sink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Sink.cpp.o
.PHONY : trunk/Live/Sink.cpp.o

trunk/Live/Sink.i: trunk/Live/Sink.cpp.i
.PHONY : trunk/Live/Sink.i

# target to preprocess a source file
trunk/Live/Sink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Sink.cpp.i
.PHONY : trunk/Live/Sink.cpp.i

trunk/Live/Sink.s: trunk/Live/Sink.cpp.s
.PHONY : trunk/Live/Sink.s

# target to generate assembly for a file
trunk/Live/Sink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/Sink.cpp.s
.PHONY : trunk/Live/Sink.cpp.s

trunk/Live/TcpConnection.o: trunk/Live/TcpConnection.cpp.o
.PHONY : trunk/Live/TcpConnection.o

# target to build an object file
trunk/Live/TcpConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/TcpConnection.cpp.o
.PHONY : trunk/Live/TcpConnection.cpp.o

trunk/Live/TcpConnection.i: trunk/Live/TcpConnection.cpp.i
.PHONY : trunk/Live/TcpConnection.i

# target to preprocess a source file
trunk/Live/TcpConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/TcpConnection.cpp.i
.PHONY : trunk/Live/TcpConnection.cpp.i

trunk/Live/TcpConnection.s: trunk/Live/TcpConnection.cpp.s
.PHONY : trunk/Live/TcpConnection.s

# target to generate assembly for a file
trunk/Live/TcpConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Live/TcpConnection.cpp.s
.PHONY : trunk/Live/TcpConnection.cpp.s

trunk/Scheduler/Event.o: trunk/Scheduler/Event.cpp.o
.PHONY : trunk/Scheduler/Event.o

# target to build an object file
trunk/Scheduler/Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Event.cpp.o
.PHONY : trunk/Scheduler/Event.cpp.o

trunk/Scheduler/Event.i: trunk/Scheduler/Event.cpp.i
.PHONY : trunk/Scheduler/Event.i

# target to preprocess a source file
trunk/Scheduler/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Event.cpp.i
.PHONY : trunk/Scheduler/Event.cpp.i

trunk/Scheduler/Event.s: trunk/Scheduler/Event.cpp.s
.PHONY : trunk/Scheduler/Event.s

# target to generate assembly for a file
trunk/Scheduler/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Event.cpp.s
.PHONY : trunk/Scheduler/Event.cpp.s

trunk/Scheduler/EventScheduler.o: trunk/Scheduler/EventScheduler.cpp.o
.PHONY : trunk/Scheduler/EventScheduler.o

# target to build an object file
trunk/Scheduler/EventScheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/EventScheduler.cpp.o
.PHONY : trunk/Scheduler/EventScheduler.cpp.o

trunk/Scheduler/EventScheduler.i: trunk/Scheduler/EventScheduler.cpp.i
.PHONY : trunk/Scheduler/EventScheduler.i

# target to preprocess a source file
trunk/Scheduler/EventScheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/EventScheduler.cpp.i
.PHONY : trunk/Scheduler/EventScheduler.cpp.i

trunk/Scheduler/EventScheduler.s: trunk/Scheduler/EventScheduler.cpp.s
.PHONY : trunk/Scheduler/EventScheduler.s

# target to generate assembly for a file
trunk/Scheduler/EventScheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/EventScheduler.cpp.s
.PHONY : trunk/Scheduler/EventScheduler.cpp.s

trunk/Scheduler/Poller.o: trunk/Scheduler/Poller.cpp.o
.PHONY : trunk/Scheduler/Poller.o

# target to build an object file
trunk/Scheduler/Poller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Poller.cpp.o
.PHONY : trunk/Scheduler/Poller.cpp.o

trunk/Scheduler/Poller.i: trunk/Scheduler/Poller.cpp.i
.PHONY : trunk/Scheduler/Poller.i

# target to preprocess a source file
trunk/Scheduler/Poller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Poller.cpp.i
.PHONY : trunk/Scheduler/Poller.cpp.i

trunk/Scheduler/Poller.s: trunk/Scheduler/Poller.cpp.s
.PHONY : trunk/Scheduler/Poller.s

# target to generate assembly for a file
trunk/Scheduler/Poller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Poller.cpp.s
.PHONY : trunk/Scheduler/Poller.cpp.s

trunk/Scheduler/SelectPoller.o: trunk/Scheduler/SelectPoller.cpp.o
.PHONY : trunk/Scheduler/SelectPoller.o

# target to build an object file
trunk/Scheduler/SelectPoller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/SelectPoller.cpp.o
.PHONY : trunk/Scheduler/SelectPoller.cpp.o

trunk/Scheduler/SelectPoller.i: trunk/Scheduler/SelectPoller.cpp.i
.PHONY : trunk/Scheduler/SelectPoller.i

# target to preprocess a source file
trunk/Scheduler/SelectPoller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/SelectPoller.cpp.i
.PHONY : trunk/Scheduler/SelectPoller.cpp.i

trunk/Scheduler/SelectPoller.s: trunk/Scheduler/SelectPoller.cpp.s
.PHONY : trunk/Scheduler/SelectPoller.s

# target to generate assembly for a file
trunk/Scheduler/SelectPoller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/SelectPoller.cpp.s
.PHONY : trunk/Scheduler/SelectPoller.cpp.s

trunk/Scheduler/SocketsOps.o: trunk/Scheduler/SocketsOps.cpp.o
.PHONY : trunk/Scheduler/SocketsOps.o

# target to build an object file
trunk/Scheduler/SocketsOps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/SocketsOps.cpp.o
.PHONY : trunk/Scheduler/SocketsOps.cpp.o

trunk/Scheduler/SocketsOps.i: trunk/Scheduler/SocketsOps.cpp.i
.PHONY : trunk/Scheduler/SocketsOps.i

# target to preprocess a source file
trunk/Scheduler/SocketsOps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/SocketsOps.cpp.i
.PHONY : trunk/Scheduler/SocketsOps.cpp.i

trunk/Scheduler/SocketsOps.s: trunk/Scheduler/SocketsOps.cpp.s
.PHONY : trunk/Scheduler/SocketsOps.s

# target to generate assembly for a file
trunk/Scheduler/SocketsOps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/SocketsOps.cpp.s
.PHONY : trunk/Scheduler/SocketsOps.cpp.s

trunk/Scheduler/Thread.o: trunk/Scheduler/Thread.cpp.o
.PHONY : trunk/Scheduler/Thread.o

# target to build an object file
trunk/Scheduler/Thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Thread.cpp.o
.PHONY : trunk/Scheduler/Thread.cpp.o

trunk/Scheduler/Thread.i: trunk/Scheduler/Thread.cpp.i
.PHONY : trunk/Scheduler/Thread.i

# target to preprocess a source file
trunk/Scheduler/Thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Thread.cpp.i
.PHONY : trunk/Scheduler/Thread.cpp.i

trunk/Scheduler/Thread.s: trunk/Scheduler/Thread.cpp.s
.PHONY : trunk/Scheduler/Thread.s

# target to generate assembly for a file
trunk/Scheduler/Thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Thread.cpp.s
.PHONY : trunk/Scheduler/Thread.cpp.s

trunk/Scheduler/ThreadPool.o: trunk/Scheduler/ThreadPool.cpp.o
.PHONY : trunk/Scheduler/ThreadPool.o

# target to build an object file
trunk/Scheduler/ThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/ThreadPool.cpp.o
.PHONY : trunk/Scheduler/ThreadPool.cpp.o

trunk/Scheduler/ThreadPool.i: trunk/Scheduler/ThreadPool.cpp.i
.PHONY : trunk/Scheduler/ThreadPool.i

# target to preprocess a source file
trunk/Scheduler/ThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/ThreadPool.cpp.i
.PHONY : trunk/Scheduler/ThreadPool.cpp.i

trunk/Scheduler/ThreadPool.s: trunk/Scheduler/ThreadPool.cpp.s
.PHONY : trunk/Scheduler/ThreadPool.s

# target to generate assembly for a file
trunk/Scheduler/ThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/ThreadPool.cpp.s
.PHONY : trunk/Scheduler/ThreadPool.cpp.s

trunk/Scheduler/Timer.o: trunk/Scheduler/Timer.cpp.o
.PHONY : trunk/Scheduler/Timer.o

# target to build an object file
trunk/Scheduler/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Timer.cpp.o
.PHONY : trunk/Scheduler/Timer.cpp.o

trunk/Scheduler/Timer.i: trunk/Scheduler/Timer.cpp.i
.PHONY : trunk/Scheduler/Timer.i

# target to preprocess a source file
trunk/Scheduler/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Timer.cpp.i
.PHONY : trunk/Scheduler/Timer.cpp.i

trunk/Scheduler/Timer.s: trunk/Scheduler/Timer.cpp.s
.PHONY : trunk/Scheduler/Timer.s

# target to generate assembly for a file
trunk/Scheduler/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/Timer.cpp.s
.PHONY : trunk/Scheduler/Timer.cpp.s

trunk/Scheduler/UsageEnvironment.o: trunk/Scheduler/UsageEnvironment.cpp.o
.PHONY : trunk/Scheduler/UsageEnvironment.o

# target to build an object file
trunk/Scheduler/UsageEnvironment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/UsageEnvironment.cpp.o
.PHONY : trunk/Scheduler/UsageEnvironment.cpp.o

trunk/Scheduler/UsageEnvironment.i: trunk/Scheduler/UsageEnvironment.cpp.i
.PHONY : trunk/Scheduler/UsageEnvironment.i

# target to preprocess a source file
trunk/Scheduler/UsageEnvironment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/UsageEnvironment.cpp.i
.PHONY : trunk/Scheduler/UsageEnvironment.cpp.i

trunk/Scheduler/UsageEnvironment.s: trunk/Scheduler/UsageEnvironment.cpp.s
.PHONY : trunk/Scheduler/UsageEnvironment.s

# target to generate assembly for a file
trunk/Scheduler/UsageEnvironment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/Scheduler/UsageEnvironment.cpp.s
.PHONY : trunk/Scheduler/UsageEnvironment.cpp.s

trunk/main.o: trunk/main.cpp.o
.PHONY : trunk/main.o

# target to build an object file
trunk/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/main.cpp.o
.PHONY : trunk/main.cpp.o

trunk/main.i: trunk/main.cpp.i
.PHONY : trunk/main.i

# target to preprocess a source file
trunk/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/main.cpp.i
.PHONY : trunk/main.cpp.i

trunk/main.s: trunk/main.cpp.s
.PHONY : trunk/main.s

# target to generate assembly for a file
trunk/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BXC_RtspServer.dir/build.make CMakeFiles/BXC_RtspServer.dir/trunk/main.cpp.s
.PHONY : trunk/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BXC_RtspServer"
	@echo "... trunk/Live/AACFileMediaSource.o"
	@echo "... trunk/Live/AACFileMediaSource.i"
	@echo "... trunk/Live/AACFileMediaSource.s"
	@echo "... trunk/Live/AACFileSink.o"
	@echo "... trunk/Live/AACFileSink.i"
	@echo "... trunk/Live/AACFileSink.s"
	@echo "... trunk/Live/Buffer.o"
	@echo "... trunk/Live/Buffer.i"
	@echo "... trunk/Live/Buffer.s"
	@echo "... trunk/Live/H264FileMediaSource.o"
	@echo "... trunk/Live/H264FileMediaSource.i"
	@echo "... trunk/Live/H264FileMediaSource.s"
	@echo "... trunk/Live/H264FileSink.o"
	@echo "... trunk/Live/H264FileSink.i"
	@echo "... trunk/Live/H264FileSink.s"
	@echo "... trunk/Live/InetAddress.o"
	@echo "... trunk/Live/InetAddress.i"
	@echo "... trunk/Live/InetAddress.s"
	@echo "... trunk/Live/MediaSession.o"
	@echo "... trunk/Live/MediaSession.i"
	@echo "... trunk/Live/MediaSession.s"
	@echo "... trunk/Live/MediaSessionManager.o"
	@echo "... trunk/Live/MediaSessionManager.i"
	@echo "... trunk/Live/MediaSessionManager.s"
	@echo "... trunk/Live/MediaSource.o"
	@echo "... trunk/Live/MediaSource.i"
	@echo "... trunk/Live/MediaSource.s"
	@echo "... trunk/Live/Rtp.o"
	@echo "... trunk/Live/Rtp.i"
	@echo "... trunk/Live/Rtp.s"
	@echo "... trunk/Live/RtspConnection.o"
	@echo "... trunk/Live/RtspConnection.i"
	@echo "... trunk/Live/RtspConnection.s"
	@echo "... trunk/Live/RtspServer.o"
	@echo "... trunk/Live/RtspServer.i"
	@echo "... trunk/Live/RtspServer.s"
	@echo "... trunk/Live/Sink.o"
	@echo "... trunk/Live/Sink.i"
	@echo "... trunk/Live/Sink.s"
	@echo "... trunk/Live/TcpConnection.o"
	@echo "... trunk/Live/TcpConnection.i"
	@echo "... trunk/Live/TcpConnection.s"
	@echo "... trunk/Scheduler/Event.o"
	@echo "... trunk/Scheduler/Event.i"
	@echo "... trunk/Scheduler/Event.s"
	@echo "... trunk/Scheduler/EventScheduler.o"
	@echo "... trunk/Scheduler/EventScheduler.i"
	@echo "... trunk/Scheduler/EventScheduler.s"
	@echo "... trunk/Scheduler/Poller.o"
	@echo "... trunk/Scheduler/Poller.i"
	@echo "... trunk/Scheduler/Poller.s"
	@echo "... trunk/Scheduler/SelectPoller.o"
	@echo "... trunk/Scheduler/SelectPoller.i"
	@echo "... trunk/Scheduler/SelectPoller.s"
	@echo "... trunk/Scheduler/SocketsOps.o"
	@echo "... trunk/Scheduler/SocketsOps.i"
	@echo "... trunk/Scheduler/SocketsOps.s"
	@echo "... trunk/Scheduler/Thread.o"
	@echo "... trunk/Scheduler/Thread.i"
	@echo "... trunk/Scheduler/Thread.s"
	@echo "... trunk/Scheduler/ThreadPool.o"
	@echo "... trunk/Scheduler/ThreadPool.i"
	@echo "... trunk/Scheduler/ThreadPool.s"
	@echo "... trunk/Scheduler/Timer.o"
	@echo "... trunk/Scheduler/Timer.i"
	@echo "... trunk/Scheduler/Timer.s"
	@echo "... trunk/Scheduler/UsageEnvironment.o"
	@echo "... trunk/Scheduler/UsageEnvironment.i"
	@echo "... trunk/Scheduler/UsageEnvironment.s"
	@echo "... trunk/main.o"
	@echo "... trunk/main.i"
	@echo "... trunk/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

